services:
  - type: web
    name: arnoldadero
    buildCommand: bun install && bun run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: CI
        value: "false"
