services:
  - type: static
    name: arnoldadero
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: CI
        value: "false"
